# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hmin <hmin@student.42seoul.kr>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/13 16:14:43 by hmin              #+#    #+#              #
#    Updated: 2020/08/13 17:56:39 by hmin             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

### Import OS image

FROM debian:buster

### Expose ports

EXPOSE 80
EXPOSE 443

### Install packages

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y apt-utils nginx vim openssl php-fpm mariadb-server php-mysql wget zsh curl git

### Setup oh-my-zsh (PURE TERMINAL..?! I can't take it anymore..!!!)

RUN zsh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

### Configure openssl

RUN openssl req -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=Lee/CN=localhost" -keyout localhost.dev.key -out localhost.dev.crt
RUN mv localhost.dev.crt /etc/ssl/certs/
RUN mv localhost.dev.key /etc/ssl/private
RUN chmod 600 /etc/ssl/certs/localhost.dev.crt /etc/ssl/private/localhost.dev.key

### Configure phpmyadmin

RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.tar.gz
RUN tar -xvf phpMyAdmin-5.0.2-all-languages.tar.gz
RUN mv phpMyAdmin-5.0.2-all-languages phpmyadmin
RUN mv phpmyadmin /var/www/html/
COPY srcs/phpmyadmin.inc.php /var/www/html/phpmyadmin/config.inc.php

### Configure wordpress

RUN wget https://wordpress.org/latest.tar.gz
RUN tar -xvf latest.tar.gz
RUN mv wordpress/ var/www/html/
RUN chown -R www-data:www-data /var/www/html/wordpress
COPY srcs/wordpress-config.php /var/www/html/wordpress/wp-config.php

### Execute container

COPY srcs/nginx.conf /etc/nginx/sites-available/default

COPY srcs/setup_db.sh /
RUN sh setup_db.sh

COPY srcs/init_container.sh /
CMD sh init_container.sh

### Thanks to yeosong
# https://yeosong1.github.io/ftserver-%ED%92%80%EC%9D%B4%EA%B8%B0%EB%A1%9D#-%EB%8F%84%EC%BB%A4%EB%A1%9C-%EB%8D%B0%EB%B9%84%EC%95%88-%EB%B2%84%EC%8A%A4%ED%84%B0-%ED%99%98%EA%B2%BD%EC%97%90-%EB%93%A4%EC%96%B4%EA%B0%80%EA%B8%B0
